---
title: "Multinomial modeling - United Kingdom"
output:
  html_document:
    df_print: paged
---


```{r}
suppressPackageStartupMessages({
  library(epicovr)
  library(tidyverse)
})
theme_set(EpicovrTheme())
```

```{r, eval=TRUE, echo=FALSE}
gisaid_metadata <- qs::qread(file = "~/github/2021_Covid19_surveillance/data/all_metadata/metadata_tsv_2022_04_15.qs")
gisaid_uk <- gisaid_metadata %>%
  filter(Country == "United Kingdom") %>%
  filter(Host == "Human")
gisaid_uk <- FormatGISAIDMetadata(gisaid_uk) 
gisaid_uk <- gisaid_uk %>% filter(State!="") %>%
  arrange(State, MonthYearCollected)
```

## Plot total sequenced cases

```{r, fig.width=8, fig.height=5, warning=FALSE}
country_seq_stats <- TotalSequencesPerMonthCountrywise(gisaid_uk, rename_country_as_state = TRUE)
p0 <- BarPlot(country_seq_stats, ylabel = "Sequenced per month", color = "slateblue1", label_si = TRUE, xangle = 90, title = "United Kingdom")
p0
```

## Get VOCs

```{r}
vocs <- GetVOCs()
omicron <- vocs[["omicron"]]
vocs[["omicron"]] <- NULL
custom_voc_mapping <- list(
  `BA.1.1` = "Omicron-BA.1.1", `BA.1` = "Omicron-BA.1",
  `BA.2` = "Omicron-BA.2"
)
for (omi in omicron) {
  if (grepl(pattern = "^BA.1", x = omi)) {
    custom_voc_mapping[[omi]] <- "Omicron-BA.1"
  } else if (grepl(pattern = "^BA.2", x = omi)) {
    custom_voc_mapping[[omi]] <- "Omicron-BA.2"
  }
}
```


```{r}
gisaid_uk_collapsed <- CollapseLineageToVOCs(
  variant_df = gisaid_uk,
  vocs = vocs,
  custom_voc_mapping = custom_voc_mapping,
  summarize = FALSE
)

gisaid_uk_collapsed_sel <- gisaid_uk_collapsed %>% filter(MonthYearCollected >= "Nov 2021") %>% filter(lineage_collapsed!="Unassigned")

vocs_to_keep <- table(gisaid_uk_collapsed_sel$lineage_collapsed)
vocs_to_keep <- vocs_to_keep[vocs_to_keep > 100]

gisaid_uk_collapsed_sel <- gisaid_uk_collapsed_sel %>% filter(lineage_collapsed %in% names(vocs_to_keep))
gisaid_uk_shared_dateweek <- SummarizeVariantsDatewise(gisaid_uk_collapsed_sel, by_state = TRUE)
head(gisaid_uk_shared_dateweek)
```

```{r}
fit_uk_multi_predsbystate <- FitMultinomStatewiseDaily(gisaid_uk_shared_dateweek)
head(fit_uk_multi_predsbystate)
```

# Plot Smooth Muller Plots

```{r, fig.width=12, fig.height=9}
muller_ukbystate_mfit <- PlotMullerDailyPrevalence(fit_uk_multi_predsbystate, ncol = 3)
muller_ukbystate_mfit
```
