---
title: "R Notebook"
output: html_notebook
---


```{r}
suppressPackageStartupMessages({
  library(epicovr)
  library(tidyverse)
})
clean_col <- function(col) {
  col <- gsub("-", " ", x = col)
  col <- gsub("–", " ", x = col)
  col <- gsub("/", " ", x = col)

  col <- gsub(pattern = ",", replacement = " ", x = col)

  col <- gsub(pattern = "-", replacement = " ", x = col)


  col <- gsub(pattern = "\\.", replacement = " ", x = col)

  col <- gsub(pattern = "\\s+", replacement = " ", x = col)

  col <- stringr::str_squish(col)

  col <- str_to_title(col)
  col[is.na(col)] <- "UNKNOWN"
  col[col == " "] <- "UNKNOWN"

  return(col)
  # col[col == ''] <- 'UNKNOWN'
}

DoCapitalise <- function(column) {
  column <- stringr::str_trim(column)
  column <- gsub("Msc", "MSC", column)
  column <- gsub("Icmr", "ICMR", column)
  column <- gsub("Csir", "CSIR", column)
  column <- gsub("Igib", "IGIB", column)
  column <- gsub("Nimhans", "NIMHANS", column)
  column <- gsub("Cdfd", "CDFD", column)
  column <- gsub("Vrdl", "VRDL", column)
  column <- gsub("Instem", "InStem", column)
  column <- gsub("Ncbs", "NCBS", column)
  column <- gsub("Insacog", "INSACOG", column)
  column <- gsub("Cdri", "CDRI", column)
  column <- gsub("Drde", "DRDE", column)
  column <- gsub("Iiser", "IISER", column)
  column <- gsub("Ncl", "NCL", column)
  column <- gsub("Aiims", "AIIMS", column)
  column <- gsub("Neist", "NEIST", column)
  column <- gsub("Ibsd", "IBSD", column)
  column <- gsub("Ilbs", "ILBS", column)
  column <- gsub("Tmc", "TMC", column)
  column <- gsub("Actrec", "ACTREC", column)
  column <- gsub("Ncdc", "NCDC", column)
  column <- gsub("Icar", "ICAR", column)
  column <- gsub("Irsha", "IRSHA", column)
  column <- gsub("Cadrad", "CADRAD", column)
  column <- gsub("And  Neuroscience ", "And  Neurosciences ", column)
  column <- gsub("IISER Pune INSACOG", "IISER Pune", column)

  column <- gsub(
    "Immunogenomics Group Institute Of Life Sciences Bhubaneswar",
    "Immunogenomics Lab Institute Of Life Sciences Bhubaneswar",
    column
  )

  column <- gsub(
    "Indian Council Of Medical Research National Institute Of Virology Maximum Containment Laboratory",
    "ICMR National Institute Of Virology", column
  )

  column <- gsub(
    "Indian Council Of Medical Research National Institute Of Virology Microbial Containment Complex",
    "ICMR National Institute Of Virology", column
  )

  column <- gsub("National Institute Of Virology Microbial Containment Complex Indian Council Of Medical Research", "ICMR National Institute Of Virology", column)
  column <- gsub(".*National Institute Of Virology.*", "ICMR National Institute Of Virology", column)

  column <- gsub(
    "Department Of Neurovirology National Institute Of Mental Health And Neuroscience \\(NIMHANS\\)",
    "Department Of Neurovirology National Institute Of Mental Health And Neurosciences \\(NIMHANS\\)",
    column
  )

  column <- gsub("Ka NIMHANS", "Department Of Neurovirology National Institute Of Mental Health And Neurosciences \\(NIMHANS\\)", column)

  column <- gsub(".*Osmania University.*", "Osmania University", column)
  column <- gsub(".*CSIR Institute Of Genomics And Integrative Biology.*", "CSIR IGIB", column)
  column <- gsub("Rf IISER Pune", "IISER Pune", column)
  column <- gsub("Niv Influenza", "ICMR National Institute Of Virology", column)

  return(column)
}


StripINSACOG <- function(column) {
  column <- gsub(" – INSACOG", "", column)
  column <- gsub("INSACOG", "", column)
  column <- stringr::str_trim(column)
  return(column)
}
```


```{r}
metadata <- list()
for (file in list.files(path = "~/github/2021_Covid19_surveillance/data/gisaid_metadata/submission_date_wise_with_auspice/", pattern = "*\\.metadata.tsv", full.names = T, recursive = T)) {
  date_path <- unlist(stringi::stri_split_fixed(file, "/"))
  date_path <- date_path[length(date_path) - 1]
  df <- read.csv(file, sep = "\t")
  df$date <- as.Date(df$date, format = "%Y-%m-%d")
  df$date_submitted <- as.Date(df$date_submitted, format = "%Y-%m-%d")
  df$`Collection date` <- df$date
  df$`Submission date` <- df$date_submitted

  df$age <- as.character(df$age)
  metadata[[date_path]] <- df
  print(date_path)
}

gisaid_metadata <- bind_rows(metadata)
gisaid_metadata <- gisaid_metadata[!duplicated(gisaid_metadata), ]
gisaid_metadata$State <- gisaid_metadata$division
gisaid_metadata$District <- gisaid_metadata$location

gisaid_metadata <- FormatGISAIDMetadata(gisaid_metadata)

gisaid_metadata$originating_lab_clean <- StripINSACOG(DoCapitalise(clean_col(gisaid_metadata$originating_lab)))


labs_reference <- data.table::fread(here::here("vignettes/INSACOG_labs.tsv")) %>% as_tibble()

gisaid_metadata$submitting_lab_clean <- StripINSACOG(DoCapitalise(clean_col(gisaid_metadata$submitting_lab)))

gisaid_metadata <- left_join(gisaid_metadata, labs_reference)

gisaid_metadata_summary <- gisaid_metadata %>%
  group_by(MonthYearCollected, submitting_lab_short) %>%
  summarise(n = n())

gisaid_metadata_summary2 <- gisaid_metadata %>%
  group_by(submitting_lab_short) %>%
  summarise(n = n()) %>% arrange(desc(n))
```
