---
title: "Animation of projected weekly cases - India"
output:
  html_document:
    df_print: paged
---




```{r}
suppressPackageStartupMessages({
  library(epicovr)
  library(tidyverse)
})
theme_set(EpicovrTheme())
```

# Get variants data for India

```{r, warning=FALSE, message=FALSE}
gisaid_metadata <- qs::qread("~/github/2021_Covid19_surveillance/data/all_metadata/metadata_tsv_2022_05_01.qs")
gisaid_india <- FilterGISAIDIndia(gisaid_metadata_all = gisaid_metadata)

vocs <- GetVOCs()
omicron <- vocs[["omicron"]]
vocs[["omicron"]] <- NULL
custom_voc_mapping <- list(
  `BA.1.1` = "Omicron-BA.1.1", `BA.1` = "Omicron-BA.1",
  `BA.2` = "Omicron-BA.2", 
  `BA.2.1` = "Omicron-BA.2", 
  `BA.2.10` = "BA.2.10",
  `BA.2.10.1` = "BA.2.10",
  `BA.2.12` = "BA.2.12",
  `BA.2.12.1` = "BA.2.12",
  `BA.3` = "Omicron-BA.3",
  `BA.4` = "Omicron-BA.4",
  `BA.5` = "Omicron-BA.5"
)
gisaid_india <- gisaid_india %>% filter(pangolin_lineage != "None")

gisaid_india <- CollapseLineageToVOCs(
  variant_df = gisaid_india,
  vocs = vocs,
  custom_voc_mapping = custom_voc_mapping,
  summarize = FALSE
)
```

# Get weekly cases for India

```{r, warning=FALSE, message=FALSE}
confirmed_subset_dateweekwise_long <- GetIndiaConfirmedCasesWeeklyLong()

confirmed_subset_dateweekwise_long_india <- confirmed_subset_dateweekwise_long %>%
  filter(State == "India") %>%
  rename(n = value) %>%
  rename(WeekYearCollected = WeekYear) %>%
  dplyr::select(-contains("type"))
confirmed_subset_dateweekwise_long_india$State <- NULL
gisaid_india_weekwise <- SummarizeVariantsWeekwise(gisaid_india)
```


# Project weekly cases to variant prevalence data from GISAID

```{r, warning=FALSE, message=FALSE}
voc_to_keep <- gisaid_india_weekwise %>%
  group_by(lineage_collapsed) %>%
  summarise(n_sum = sum(n)) %>%
  filter(n_sum > 50) %>%
  pull(lineage_collapsed) %>%
  unique()
gisaid_india_weekwise <- gisaid_india_weekwise %>% filter(lineage_collapsed %in% voc_to_keep)

india_cases_pred_prob_sel_long <- FitMultinomWeekly(gisaid_india_weekwise, confirmed_subset_dateweekwise_long_india)
the_anim <- PlotVariantPrevalenceAnimated(india_cases_pred_prob_sel_long, title = "Estimated cases (weekly average) in India by variant")
the_anim
```
