---
title: "Animation of projected weekly cases - USA"
output:
  html_document:
    df_print: paged
---




```{r}
suppressPackageStartupMessages({
  library(epicovr)
  library(covid19nytimes)
  library(tidyverse)
})
theme_set(EpicovrTheme())
```

# Get variants data for NYC

```{r, warning=FALSE, message=FALSE}
gisaid_metadata <- qs::qread("~/github/2021_Covid19_surveillance/data/all_metadata/metadata_tsv_2022_05_03.qs")
gisaid_usa <- gisaid_metadata %>%
  filter(Country == "USA") %>%
  filter(Host == "Human")
# format metadata
gisaid_usa <- FormatGISAIDMetadata(gisaid_usa)
gisaid_usa <- gisaid_usa %>%
  arrange(State, MonthYearCollected) %>%
  filter(pangolin_lineage != "Unknown")

vocs <- GetVOCs()
omicron <- vocs[["omicron"]]
vocs[["omicron"]] <- NULL
vocs[["lambda"]] <- NULL
vocs[["beta"]] <- NULL
vocs[["gamma"]] <- NULL

custom_voc_mapping <- list(
  `BA.1.1` = "BA.1.1", 
  `BA.1` = "BA.1",
  `BA.2` = "BA.2",
  `BA.2.1` = "BA.2.1",
  `BA.2.9` = "BA.2.9",
  `BA.1.17.2` = "BA.1.17.2",
  `BA.2.10` = "BA.2.10",
  `BA.2.10.1` = "BA.2.10.1",
  `BA.2.12` = "BA.2.12",
  `BA.2.12.1` = "BA.2.12.1"
)
gisaid_usa <- gisaid_usa %>% filter(pangolin_lineage != "None")

gisaid_usa <- CollapseLineageToVOCs(
  variant_df = gisaid_usa,
  vocs = vocs,
  custom_voc_mapping = custom_voc_mapping,
  summarize = FALSE
)
```

# Get weekly cases for USA

```{r, warning=FALSE, message=FALSE}

all_state_cases <- refresh_covid19nytimes_states()

confirmed.tmp <- all_state_cases %>%
  filter(data_type == "cases_total") %>%
  arrange(date)
confirmed <- confirmed.tmp %>% group_by(date) %>% summarise(value = sum(value))

confirmed$daily_cases <- c(confirmed$value[1], diff(confirmed$value))
confirmed$WeekYear <- tsibble::yearweek(confirmed$date)

confirmed_subset_dateweekwise_long <- confirmed %>%
  group_by(WeekYear) %>%
  summarise(n = sum(daily_cases)) %>%
  arrange(WeekYear) %>%
  rename(WeekYearCollected = WeekYear)

gisaid_usa_weekwise <- SummarizeVariantsWeekwise(gisaid_usa)
```


# Project weekly cases to variant prevalence data from GISAID

```{r, warning=FALSE, message=FALSE}
voc_to_keep <- gisaid_usa_weekwise %>%
  group_by(lineage_collapsed) %>%
  summarise(n_sum = sum(n)) %>%
  filter(n_sum > 50) %>%
  pull(lineage_collapsed) %>%
  unique()
gisaid_usa_weekwise <- gisaid_usa_weekwise %>% filter(lineage_collapsed %in% voc_to_keep)

usa_cases_pred_prob_sel_long <- FitMultinomWeekly(gisaid_usa_weekwise, confirmed_subset_dateweekwise_long)
the_anim <- PlotVariantPrevalenceAnimated(usa_cases_pred_prob_sel_long, title = "Estimated cases (weekly average) in the USA by variant", caption = "**Source: gisaid.org and covid19nytimes<br>**")
the_anim
```


Look at cases after October,2021 only:

```{r}

confirmed$MonthYear <- GetMonthYear(confirmed$date)

confirmed_subset_dateweekwise_long <- confirmed %>% filter(MonthYear>"Oct 2021") %>%
  group_by(WeekYear) %>%
  summarise(n = sum(daily_cases)) %>%
  arrange(WeekYear) %>%
  rename(WeekYearCollected = WeekYear)

gisaid_usa_subset <- gisaid_usa %>% filter(MonthYearCollected > "Oct 2021")
gisaid_usa_weekwise <- SummarizeVariantsWeekwise(gisaid_usa_subset)

voc_to_keep <- gisaid_usa_weekwise %>%
  group_by(lineage_collapsed) %>%
  summarise(n_sum = sum(n)) %>%
  filter(n_sum > 50) %>%
  pull(lineage_collapsed) %>%
  unique()
gisaid_usa_weekwise <- gisaid_usa_weekwise %>% filter(lineage_collapsed %in% voc_to_keep)

usa_cases_pred_prob_sel_long <- FitMultinomWeekly(gisaid_usa_weekwise, confirmed_subset_dateweekwise_long)
the_anim <- PlotVariantPrevalenceAnimated(usa_cases_pred_prob_sel_long, title = "Estimated cases (weekly average) in the USA by variant", caption = "**Source: gisaid.org and covid19nytimes<br>**")
the_anim
```
