---
title: "Animation of projected weekly cases - New York State"
output:
  html_document:
    df_print: paged
---




```{r}
suppressPackageStartupMessages({
  library(epicovr)
  library(covid19nytimes)
  library(tidyverse)
})
theme_set(EpicovrTheme())
```

# Get variants data for NYC

```{r, warning=FALSE, message=FALSE}
gisaid_metadata <- qs::qread("~/github/2021_Covid19_surveillance/data/all_metadata/metadata_tsv_2022_04_27.qs")
gisaid_usa <- gisaid_metadata %>%
  filter(Country == "USA") %>%
  filter(Host == "Human")
# format metadata
gisaid_usa <- FormatGISAIDMetadata(gisaid_usa)
gisaid_usa <- gisaid_usa %>%
  arrange(State, MonthYearCollected) %>%
  filter(pangolin_lineage != "Unknown")
gisaid_NY <- gisaid_usa %>% filter(State == "New York")

vocs <- GetVOCs()
omicron <- vocs[["omicron"]]
vocs[["omicron"]] <- NULL
custom_voc_mapping <- list(
  `BA.1.1` = "Omicron-BA.1.1", `BA.1` = "Omicron-BA.1",
  `BA.2` = "Omicron-BA.2",
  `BA.2.1` = "Omicron-BA.2",
  `BA.2.10` = "BA.2.10",
  `BA.2.10.1` = "BA.2.10",
  `BA.2.12` = "BA.2.12",
  `BA.2.12.1` = "BA.2.12",
  `BA.3` = "Omicron-BA.3",
  `BA.4` = "Omicron-BA.4",
  `BA.5` = "Omicron-BA.5"
)
gisaid_NY <- gisaid_NY %>% filter(pangolin_lineage != "None")

gisaid_NY <- CollapseLineageToVOCs(
  variant_df = gisaid_NY,
  vocs = vocs,
  custom_voc_mapping = custom_voc_mapping,
  summarize = FALSE
)
```

# Get weekly cases for New York

```{r, warning=FALSE, message=FALSE}

all_state_cases <- refresh_covid19nytimes_states()

confirmed <- all_state_cases %>%
  filter(location == "New York") %>%
  filter(data_type == "cases_total") %>%
  arrange(date)

confirmed$daily_cases <- c(confirmed$value[1], diff(confirmed$value))
confirmed$WeekYear <- tsibble::yearweek(confirmed$date)

confirmed_subset_dateweekwise_long <- confirmed %>%
  group_by(WeekYear) %>%
  summarise(n = sum(daily_cases)) %>%
  arrange(WeekYear) %>%
  rename(WeekYearCollected = WeekYear)

gisaid_NY_weekwise <- SummarizeVariantsWeekwise(gisaid_NY)
```


# Project weekly cases to variant prevalence data from GISAID

```{r, warning=FALSE, message=FALSE}
voc_to_keep <- gisaid_NY_weekwise %>%
  group_by(lineage_collapsed) %>%
  summarise(n_sum = sum(n)) %>%
  filter(n_sum > 50) %>%
  pull(lineage_collapsed) %>%
  unique()
gisaid_NY_weekwise <- gisaid_NY_weekwise %>% filter(lineage_collapsed %in% voc_to_keep)

newyork_cases_pred_prob_sel_long <- FitMultinomWeekly(gisaid_NY_weekwise, confirmed_subset_dateweekwise_long)
the_anim <- PlotVariantPrevalenceAnimated(newyork_cases_pred_prob_sel_long, title = "Estimated cases (weekly average) in New York state by variant")
the_anim
```
